### ISSUE TITLE
AttributeError: 'SQLA' object has no attribute 'engine'

### ISSUE THREAD

**Issue by Kloping** [RBAmeto/gsuidcore_mys_qrlogin#3]
最新版
future: <Task finished name='Task-1092' coro=<one_more_thing() done, defined at /gsuid_core/gsuid_core/plugins/gsuidcore_mys_qrlogin/__init__.py:8> exception=AttributeError("'SQLA' object has no attribute 'engine'")>
Traceback (most recent call last):
  File "/gsuid_core/gsuid_core/plugins/gsuidcore_mys_qrlogin/__init__.py", line 40, in one_more_thing
    msg = await qrlogin_game(url,qid,bid)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gsuid_core/gsuid_core/plugins/gsuidcore_mys_qrlogin/qrlogin.py", line 54, in qrlogin_game
    sqla = get_sqla(bid)
           ^^^^^^^^^^^^^
  File "/gsuid_core/gsuid_core/plugins/gsuidcore_mys_qrlogin/qrlogin.py", line 38, in get_sqla
    @event.listens_for(sqla.engine.sync_engine, 'connect')
                       ^^^^^^^^^^^
AttributeError: 'SQLA' object has no attribute 'engine'
![image](https://github.com/RBAmeto/gsuidcore_mys_qrlogin/assets/87743020/6c00b559-3952-4936-9476-42f319aaa6f5)

**Comment by RBAmeto** [comment]
gscore更新了，已修复
